server:
  port: 8080

spring:
  application:
    name: geduc
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.0lnyvmd.mongodb.net/?retryWrites=true&w=majority
      port: 27017
      database: geduc
    azure:
      container: geduc
      connection-string: https://geduc.blob.core.windows.net/
      token: ?sv=2021-06-08&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2022-10-14T05:54:49Z&st=2022-10-13T21:54:49Z&spr=https&sig=cppvDV8dUEgbZjcg0%2BuUmLg5huzvQgyd3jzbhRzaTg4%3D