server:
  port: 8080

spring:
  application:
    name: geduc
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://admin:admin@cluster0.0lnyvmd.mongodb.net/?retryWrites=true&w=majority}
      port: 27017
      database: geduc