server:
  port: 8080

spring:
  application:
    name: geduc
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.0lnyvmd.mongodb.net/?retryWrites=true&w=majority
      port: 27017
      database: geduc
    azure:
      container: geduc
      connection-string: https://geduc2.blob.core.windows.net/
      token: sp=racwdli&st=2022-11-21T16:37:43Z&se=2023-01-18T00:37:43Z&sv=2021-06-08&sr=c&sig=S8qst4FZq4PMvJGzgWkLFn2aZ81kSdWn%2FNahrCkUJbc%3D