server:
  port: 8080

spring:
  profiles:
    active: ${APP_PROFILE:dev}
  application:
    name: geduc
  data:
    mongodb:
      uri: ${MONGODB_URI}
      port: 27017
      database: geduc
    azure:
      container: ${AZURE_CONTAINER}
      connection-string: ${AZURE_CONNECTION_STRING}
      token: ${AZURE_TOKEN}