server:
  port: 8080

spring:
  application:
    name: geduc
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.0lnyvmd.mongodb.net/?retryWrites=true&w=majority
      port: 27017
      database: geduc
    azure:
      container: geduc
      connection-string: https://geduc.blob.core.windows.net/
      token: sp=racwdli&st=2022-10-14T19:41:11Z&se=2024-01-01T03:41:11Z&sv=2021-06-08&sr=c&sig=mJLkdTBTOys10OkjdsDzDcTsIQsanVLyy%2FJ7Kj%2BzduE%3D